### ISSUE TITLE
JSON: convert oneOf -> anyOf when safe

### ISSUE THREAD

**Issue by mmoskal** [guidance-ai/llguidance#77]
Not urgent, but logging it for tracking:
- we currently have an option to approximate all `oneOf` as `anyOf`, which is unsound
- instead, we could check for a given `oneOf` if it is always equivalent to `anyOf`, in particular if it's something like an enum, or it has a discriminator field

**Comment by hudson-ai** [comment]
Resolved by #94 , although additional cases can probably be marked safe
