### ISSUE TITLE
compile enums as regexes, not grammars

### ISSUE THREAD

**Issue by mmoskal** [guidance-ai/llguidance#84]
We should try to compile enums into a regex if possible.

Size distribution of enum sizes below - there is on the order of 100 cases with more than 200 enum items (which will blow the parser), and even for smaller ones regexes will be faster.

| Enum size | Num. schemas |
| ---- | ----- |
| 1    | 1920 |
| 2    | 1293 |
| 3-4    | 1763 |
| 5-8    | 957 |
| 9-16   | 444 |
| 17-32   | 390 |
| 33-64   | 263 |
| 65-128  | 88 |
| 129-256  | 51 |
| 257-512  | 15 |
| 513-1024 | 8 |
| 1025-2048    | 2 |
| 2049-4096    | 6 |
| 4097-8192    | 1 |

**Comment by hudson-ai** [comment]
@mmoskal do you know if these are mostly string enums?

**Comment by mmoskal** [comment]
among the non-synthesized cases:

```
  "enum:string_or_null": 3415,
  "enum:number_or_null": 143,
  "enum:boolean_or_null": 60,
  "enum:primitive": 44,
  "enum:mixed": 8
```


Where `primitive` means other combination of string, number, boolean, null.

The `mixed` cases are all weird.

**Comment by hudson-ai** [comment]
just to do something quick and pragmatic -- it would be easy to rewrite the string enums as Schema::String variants with an alternation for the pattern. We could allow nullability by wrapping that in a Schema::OneOf -- would this take care of most or all of the "large" enums?

**Comment by mmoskal** [comment]
I would add `is_const()` method `Schema`, plus a `const_val: Option<String>` to `Schema::String`; then additional method `const_compile() -> Option<String>`; then when compiling AnyOf you check if they are all const and if so map with const_compile() and do an OR

**Comment by mmoskal** [comment]
Couldn't help myself #91 ;)

**Comment by hudson-ai** [comment]
@mmoskal good man!! I'll take a look later :)
